// Generated by Babel
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.newRequest = newRequest;
exports.resolveUrl = resolveUrl;

//var _resolveUrl = require("resolve-url");

// var _resolveUrl = require("resolve-pathname");
var _urlParse = require("url-parse");

var _urlParse2 = _interopRequireDefault(_urlParse);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function newRequest() {
  return new window.XMLHttpRequest();
} /* global window */


function resolveUrl(origin, link) {

  // return (0, _resolveUrl2.default)(origin, link);
  return new _urlParse2.default(link, origin).toString();
}

